// Code generated by rescodegen. DO NOT EDIT.

package main

import (
	"github.com/restayway/rescode"
	"google.golang.org/grpc/codes"
)

// Error code constants
const (
	AuthenticationFailedCode uint64     = 10001
	AuthenticationFailedHTTP int        = 401
	AuthenticationFailedGRPC codes.Code = 16
	AuthenticationFailedMsg  string     = "Authentication failed"
	AuthenticationFailedDesc string     = "The provided credentials are invalid"

	AuthorizationDeniedCode uint64     = 10002
	AuthorizationDeniedHTTP int        = 403
	AuthorizationDeniedGRPC codes.Code = 7
	AuthorizationDeniedMsg  string     = "Authorization denied"
	AuthorizationDeniedDesc string     = "User does not have permission to perform this action"

	PolicyNotFoundCode uint64     = 20001
	PolicyNotFoundHTTP int        = 404
	PolicyNotFoundGRPC codes.Code = 5
	PolicyNotFoundMsg  string     = "Policy not found"
	PolicyNotFoundDesc string     = "Policy could not be located in the database"

	InvalidPolicyKindCode uint64     = 20002
	InvalidPolicyKindHTTP int        = 400
	InvalidPolicyKindGRPC codes.Code = 3
	InvalidPolicyKindMsg  string     = "Invalid policy kind"
	InvalidPolicyKindDesc string     = "Policy kind is not supported"

	RateLimitExceededCode uint64     = 30001
	RateLimitExceededHTTP int        = 429
	RateLimitExceededGRPC codes.Code = 8
	RateLimitExceededMsg  string     = "Rate limit exceeded"
	RateLimitExceededDesc string     = "Request rate limit has been exceeded"

	InternalServerErrorCode uint64     = 99999
	InternalServerErrorHTTP int        = 500
	InternalServerErrorGRPC codes.Code = 13
	InternalServerErrorMsg  string     = "Internal server error"
	InternalServerErrorDesc string     = "An unexpected internal error occurred"
)

// AuthenticationFailed creates a new AuthenticationFailed error.
// The provided credentials are invalid
func AuthenticationFailed(err ...error) *rescode.RC {
	return rescode.New(AuthenticationFailedCode, AuthenticationFailedHTTP, AuthenticationFailedGRPC, AuthenticationFailedMsg)(err...)
}

// AuthorizationDenied creates a new AuthorizationDenied error.
// User does not have permission to perform this action
func AuthorizationDenied(err ...error) *rescode.RC {
	return rescode.New(AuthorizationDeniedCode, AuthorizationDeniedHTTP, AuthorizationDeniedGRPC, AuthorizationDeniedMsg)(err...)
}

// PolicyNotFound creates a new PolicyNotFound error.
// Policy could not be located in the database
func PolicyNotFound(err ...error) *rescode.RC {
	return rescode.New(PolicyNotFoundCode, PolicyNotFoundHTTP, PolicyNotFoundGRPC, PolicyNotFoundMsg)(err...)
}

// InvalidPolicyKind creates a new InvalidPolicyKind error.
// Policy kind is not supported
func InvalidPolicyKind(err ...error) *rescode.RC {
	return rescode.New(InvalidPolicyKindCode, InvalidPolicyKindHTTP, InvalidPolicyKindGRPC, InvalidPolicyKindMsg)(err...)
}

// RateLimitExceeded creates a new RateLimitExceeded error.
// Request rate limit has been exceeded
func RateLimitExceeded(err ...error) *rescode.RC {
	return rescode.New(RateLimitExceededCode, RateLimitExceededHTTP, RateLimitExceededGRPC, RateLimitExceededMsg)(err...)
}

// InternalServerError creates a new InternalServerError error.
// An unexpected internal error occurred
func InternalServerError(err ...error) *rescode.RC {
	return rescode.New(InternalServerErrorCode, InternalServerErrorHTTP, InternalServerErrorGRPC, InternalServerErrorMsg)(err...)
}
