// Code generated by rescodegen. DO NOT EDIT.

package testdata

import (
	"github.com/restayway/rescode"
	"google.golang.org/grpc/codes"
)

// Error code constants
const (
	PolicyNotFoundCode uint64     = 20001
	PolicyNotFoundHTTP int        = 404
	PolicyNotFoundGRPC codes.Code = 5
	PolicyNotFoundMsg  string     = "Policy not found"
	PolicyNotFoundDesc string     = "Policy could not be located in the database"

	InvalidKindCode uint64     = 20002
	InvalidKindHTTP int        = 400
	InvalidKindGRPC codes.Code = 3
	InvalidKindMsg  string     = "Invalid policy kind"
	InvalidKindDesc string     = "Policy kind is not supported"

	InternalErrorCode uint64     = 20003
	InternalErrorHTTP int        = 500
	InternalErrorGRPC codes.Code = 13
	InternalErrorMsg  string     = "Internal server error"
	InternalErrorDesc string     = "An unexpected internal error occurred"
)

// PolicyNotFound creates a new PolicyNotFound error.
// Policy could not be located in the database
func PolicyNotFound(err ...error) *rescode.RC {
	return rescode.New(PolicyNotFoundCode, PolicyNotFoundHTTP, PolicyNotFoundGRPC, PolicyNotFoundMsg)(err...)
}

// InvalidKind creates a new InvalidKind error.
// Policy kind is not supported
func InvalidKind(err ...error) *rescode.RC {
	return rescode.New(InvalidKindCode, InvalidKindHTTP, InvalidKindGRPC, InvalidKindMsg)(err...)
}

// InternalError creates a new InternalError error.
// An unexpected internal error occurred
func InternalError(err ...error) *rescode.RC {
	return rescode.New(InternalErrorCode, InternalErrorHTTP, InternalErrorGRPC, InternalErrorMsg)(err...)
}
